### ISSUE TITLE
handle: failed to parse S_PLAYER_STAT_UPDATE<12>

### ISSUE THREAD

**Issue by BamV** [Fukki/auto-pot#11]
[13:07:11.722] [dispatch] handle: failed to parse S_PLAYER_STAT_UPDATE<12>
hook: (anonymous) in autopot
data: 030188c8bfef000000000000db0c000000000000000000008a70020000000000db0c00004800000050000000320000001e0000006e0032007800000070420000544200000040f57c0200f57c0200d76c010015870000b86200000000484200004842000048420f010000840000000000000000000000810014002d00000028430000524390c2b53f94eb030094eb030074720100000000000000000000000000000000000000000041000000000001000000000000000078000000780000002c0100002c0100000000000000000000c8010000c8010000000000000000c0ff00000000000000004100000000007a44000000000000803f000000000000000000000000
error: The value of "offset" is out of range. It must be >= 0 and <= 255. Received 259
    at boundsError (internal/buffer.js:53:9)
    at Buffer.readUInt32LE (internal/buffer.js:109:5)
    at Readable.uint32 (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\stream.js:35:33)
    at parseField (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:422:37)
    at TeraProtocol.parse (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:431:7)
[13:07:11.727] [dispatch] handle: failed to parse S_PLAYER_STAT_UPDATE<12>
hook: (anonymous) in autopot
data: 030188c8bfef000000000000db0c000000000000000000008a70020000000000db0c00004800000050000000320000001e0000006e0032007800000070420000544200000040f57c0200f57c0200d76c010015870000b86200000000484200004842000048420f010000840000000000000000000000b90014002d00000028430000524390c2b53f94eb030094eb030074720100000000000000000000000000000000000000000041000000000001000000000000000078000000780000002c0100002c0100000000000000000000c8010000c8010000000000000000c0ff00000000000000004100000000007a44060000000000803f000000000000000000000000
error: The value of "offset" is out of range. It must be >= 0 and <= 255. Received 259
    at boundsError (internal/buffer.js:53:9)
    at Buffer.readUInt32LE (internal/buffer.js:109:5)
    at Readable.uint32 (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\stream.js:35:33)
    at parseField (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:422:37)
    at TeraProtocol.parse (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:431:7)
[13:07:11.735] [dispatch] handle: failed to parse S_PLAYER_STAT_UPDATE<12>
hook: (anonymous) in autopot
data: 030188c8bfef000000000000db0c000000000000000000008a70020000000000db0c00004800000050000000320000001e0000006e0032007800000070420000544200000040f57c0200f57c0200d76c010015870000b86200000000484200004842000048420f010000840000000000000000000000b90014002d00000028430000524390c2b53f94eb030094eb030074720100000000000000000000000000000000000000000041000000000001000000000000000078000000780000002c0100002c0100000000000000000000c8010000c8010000000000000000c0ff00000000000000004100000000007a44060000000000803f000000000000000000000000
error: The value of "offset" is out of range. It must be >= 0 and <= 255. Received 259
    at boundsError (internal/buffer.js:53:9)
    at Buffer.readUInt32LE (internal/buffer.js:109:5)
    at Readable.uint32 (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\stream.js:35:33)
    at parseField (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:422:37)
    at TeraProtocol.parse (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:431:7)
[13:07:11.747] [dispatch] handle: failed to parse S_PLAYER_STAT_UPDATE<12>
hook: (anonymous) in autopot
data: 030188c8bfef000000000000db0c000000000000000000008a70020000000000db0c00004800000050000000320000001e0000006e0032007800000070420000544200000040f57c0200f57c0200d76c010015870000b86200000000484200004842000048420f010000840000000000000000000000b90014002d00000028430000524390c2b53f94eb030094eb030074720100000000000000000000000000000000000000000041000000000001000000000000000078000000780000002c0100002c0100000000000000000000c8010000c8010000000000000000c0ff00000000000000004100000000007a44060000000000803f000000000000000000000000
error: The value of "offset" is out of range. It must be >= 0 and <= 255. Received 259
    at boundsError (internal/buffer.js:53:9)
    at Buffer.readUInt32LE (internal/buffer.js:109:5)
    at Readable.uint32 (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\stream.js:35:33)
    at parseField (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:422:37)
    at TeraProtocol.parse (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:431:7)
[13:07:11.763] [dispatch] handle: failed to parse S_PLAYER_STAT_UPDATE<12>
hook: (anonymous) in autopot
data: 030188c8bfef000000000000db0c000000000000000000008a70020000000000db0c00004800000050000000320000001e0000006e0032007800000070420000544200000040f57c0200f57c0200d76c010015870000b86200000000484200004842000048420f010000840000000000000000000000c30014002d00000028430000524390c2b53f94eb030094eb030074720100000000000000000000000000000000000000000041000000000001000000000000000078000000780000002c0100002c0100000000000000000000c8010000c8010000000000000000c0ff00000000000000004100000000007a44060000000000803f000000000000000000000000
error: The value of "offset" is out of range. It must be >= 0 and <= 255. Received 259
    at boundsError (internal/buffer.js:53:9)
    at Buffer.readUInt32LE (internal/buffer.js:109:5)
    at Readable.uint32 (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\stream.js:35:33)
    at parseField (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:422:37)
    at TeraProtocol.parse (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:431:7)
[13:07:12.675] [dispatch] handle: failed to parse S_INVEN<18>
hook: (anonymous) in autopot
data: 
error: The value of "offset" is out of range. It must be >= 0 and <= 24331. Received 36061
    at boundsError (internal/buffer.js:53:9)
    at Buffer.readUInt16LE (internal/buffer.js:132:5)
    at Readable.uint16 (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\stream.js:29:33)
    at parseField (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:378:31)
    at TeraProtocol.parse (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:431:7)
    at parseField (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:384:33)
    at TeraProtocol.parse (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:431:7)
[13:07:16.218] [dispatch] handle: failed to parse S_PLAYER_STAT_UPDATE<12>
hook: (anonymous) in autopot
data: 030188c86e34010000000000db0c000000000000000000008a70020000000000db0c00004800000050000000320000001e0000006e0032007800000070420000544200000040f57c0200f57c0200d76c010015870000b86200000000484200004842000048420f010000840000000000000000000000c30014002d00000028430000524390c2b53f94eb030094eb030074720100000000000000000000000000000000000000000041000000000001000000000000000078000000780000002c0100002c0100000000000000000000c8010000c8010000000000000000c0ff00000000000000004100000000006e44060000000000803f000000000000000000000000
error: The value of "offset" is out of range. It must be >= 0 and <= 255. Received 259
    at boundsError (internal/buffer.js:53:9)
    at Buffer.readUInt32LE (internal/buffer.js:109:5)
    at Readable.uint32 (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\stream.js:35:33)
    at parseField (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:422:37)
    at TeraProtocol.parse (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:431:7)
[13:07:16.526] [dispatch] handle: failed to parse S_PLAYER_STAT_UPDATE<12>
hook: (anonymous) in autopot
data: 030188c86e34010000000000db0c000000000000000000008a70020000000000db0c00004800000050000000320000001e0000006e0032007800000070420000544200000040f57c0200f57c0200d76c010015870000b86200000000484200004842000048420f010000840000000000000000000000b90014002d00000028430000524390c2b53f94eb030094eb030074720100000000000000000000000000000000000000000041000000000001000000000000000078000000780000002c0100002c0100000000000000000000c8010000c8010000000000000000c0ff00000000000000004100000000006e44060000000000803f000000000000000000000000
error: The value of "offset" is out of range. It must be >= 0 and <= 255. Received 259
    at boundsError (internal/buffer.js:53:9)
    at Buffer.readUInt32LE (internal/buffer.js:109:5)
    at Readable.uint32 (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\stream.js:35:33)
    at parseField (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:422:37)
    at TeraProtocol.parse (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:431:7)
[13:07:16.789] [dispatch] handle: failed to parse S_PLAYER_STAT_UPDATE<12>
hook: (anonymous) in autopot
data: 030188c86e34010000000000db0c000000000000000000008a70020000000000db0c00004800000050000000320000001e0000006e0032007800000070420000544200000040f57c0200f57c0200d76c010015870000b86200000000484200004842000048420f010000840000000000000000000000b90014002d00000028430000524390c2b53f94eb030094eb030074720100000000000000000000000000000000000000000041000000000001000000000000000078000000780000002c0100002c0100000000000000000000c8010000c8010000000000000000c0ff00000000000000004100000000006e44060000000000803f000000000000000000000000
error: The value of "offset" is out of range. It must be >= 0 and <= 255. Received 259
    at boundsError (internal/buffer.js:53:9)
    at Buffer.readUInt32LE (internal/buffer.js:109:5)
    at Readable.uint32 (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\stream.js:35:33)
    at parseField (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:422:37)
    at TeraProtocol.parse (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:431:7)
[13:07:17.058] [dispatch] handle: failed to parse S_PLAYER_STAT_UPDATE<12>
hook: (anonymous) in autopot
data: 030188c86e34010000000000db0c000000000000000000008a70020000000000db0c00004800000050000000320000001e0000006e0032007800000070420000544200000040f57c0200f57c0200d76c010015870000b86200000000484200004842000048420f010000840000000000000000000000b90014002d00000028430000524390c2b53f94eb030094eb030074720100000000000000000000000000000000000000000041000000000001000000000000000078000000780000002c0100002c0100000000000000000000c8010000c8010000000000000000c0ff00000000000000004100000000006e44060000000000803f000000000000000000000000
error: The value of "offset" is out of range. It must be >= 0 and <= 255. Received 259
    at boundsError (internal/buffer.js:53:9)
    at Buffer.readUInt32LE (internal/buffer.js:109:5)
    at Readable.uint32 (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\stream.js:35:33)
    at parseField (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:422:37)
    at TeraProtocol.parse (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:431:7)
[13:07:17.338] [dispatch] handle: failed to parse S_PLAYER_STAT_UPDATE<12>
hook: (anonymous) in autopot
data: 030188c86e34010000000000db0c000000000000000000008a70020000000000db0c00004800000050000000320000001e0000006e0032007800000070420000544200000040f57c0200f57c0200d76c010015870000b86200000000484200004842000048420f010000840000000000000000000000810014002d00000028430000524390c2b53f94eb030094eb030074720100000000000000000000000000000000000000000041000000000001000000000000000078000000780000002c0100002c0100000000000000000000c8010000c8010000000000000000c0ff00000000000000004100000000006e44000000000000803f000000000000000000000000
error: The value of "offset" is out of range. It must be >= 0 and <= 255. Received 259
    at boundsError (internal/buffer.js:53:9)
    at Buffer.readUInt32LE (internal/buffer.js:109:5)
    at Readable.uint32 (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\stream.js:35:33)
    at parseField (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:422:37)
    at TeraProtocol.parse (C:\Users\Tetsu\AppData\Local\Programs\CaaliTeraProxy\node_modules\tera-data-parser\lib\protocol\index.js:431:7)

**Comment by Fukki** [comment]
i have change packet to use now

**Comment by BamV** [comment]
ty
