### ISSUE TITLE
Error updating HP and MP configuration files. v85.6

### ISSUE THREAD

**Issue by war100ck** [Fukki/auto-pot#15]
`[18:55:04.292] [dispatch] [autopot] handle: error running hook for C_ADMIN<1>
hook: (anonymous) in autopot
data: { command: 'autopot reload hp' }
error: [dispatch] write: failed to generate C_SHOW_INVEN<1>:
Error: code not known for message "C_SHOW_INVEN"

[18:55:04.294] [dispatch] [badgui] handle: error running hook for C_ADMIN<1>
hook: (anonymous) in badgui
data: { command: 'autopot reload hp' }
error: [dispatch] write: failed to generate C_SHOW_INVEN<1>:
Error: code not known for message "C_SHOW_INVEN"

[18:55:04.295] [dispatch] [fps-utils] handle: error running hook for C_ADMIN<1>
hook: (anonymous) in fps-utils
data: { command: 'autopot reload hp' }
error: [dispatch] write: failed to generate C_SHOW_INVEN<1>:
Error: code not known for message "C_SHOW_INVEN"`

**Comment by Foks5000** [comment]
S_INVEN and C_SHOW_INVEN are obsolete

**Comment by Fukki** [comment]
C_SHOW_INVEN not work
now after use reload just open inventory by your self for upload the potion list

**Comment by war100ck** [comment]
The module still does not work:
`[20:04:58.423] [модули] ОШИБКА: Модуль "AutoPOT" (AutoPOT) не может быть запущен!
[20:04:58.425] [модули] ОШИБКА: Сообщите автору мода: https://github.com/Fukki/auto-pot/issues/
[20:04:58.426] Error: [dispatch] [autopot] hook: unmapped packet "S_INVEN"
    at Dispatch.createHook (C:\Users\war100ck\Downloads\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:237:23)
    at Dispatch.hook (C:\Users\war100ck\Downloads\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:282:27)
    at Module.hook (C:\Users\war100ck\Downloads\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:102:36)
    at new AutoPOT (C:\Users\war100ck\Downloads\TeraToolbox\mods\auto-pot-master\index.js:234:6)
    at ModuleManager.load (C:\Users\war100ck\Downloads\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:156:35)
    at C:\Users\war100ck\Downloads\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:121:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (C:\Users\war100ck\Downloads\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:119:31)
    at Socket.<anonymous> (C:\Users\war100ck\Downloads\TeraToolbox\bin\connectionManager.js:54:47)
    at Socket.emit (events.js:199:15)`

**Comment by Foks5000** [comment]
@Fukki  S_INVEN removed in patch 85. Use 'inventory' module from tera-game-state instead
![image](https://user-images.githubusercontent.com/2840949/64054432-4d2ae580-cbca-11e9-9b9a-ca57fc51f4f9.png)
