### ISSUE TITLE
Error after NextGen update

### ISSUE THREAD

**Issue by sunnydelete** [Fukki/auto-pot#4]
error: Cannot read property 'active' of undefined
    at Object.AutoPOT.mod.hook.e [as callback] (C:\tera-proxy\mods\autopot\index.js:81:174)
[dispatch] handle: error running hook for S_PLAYER_STAT_UPDATE<10>
hook: (anonymous) in autopot
data: { hp: 170725n,
  mp: 2630n,
  unk1: 0,
  maxHp: 170725n,
  maxMp: 3633,
  power: 50,
  endurance: 35,
  impactFactor: 40,
  balanceFactor: 70,
  runSpeed: 105,
  walkSpeed: 50,
  attackSpeed: 100,
  critRate: 50,
  critResist: 75,
  critPower: 2,
  attack: 117648,
  attack2: 117648,
  defense: 70691,
  impact: 29289,
  balance: 58712,
  resistWeakening: 45,
  resistPeriodic: 45,
  resistStun: 45,
  powerBonus: 156,
  enduranceBonus: 126,
  impactFactorBonus: 0,
  balanceFactorBonus: 20,
  runSpeedBonus: 114,
  walkSpeedBonus: 0,
  attackSpeedBonus: 33,
  critRateBonus: 296,
  critResistBonus: 220,
  critPowerBonus: 0.07999992370605469,
  attackBonus: 122353,
  attack2Bonus: 122353,
  defenseBonus: 104789,
  impactBonus: 0,
  balanceBonus: 16775,
  resistWeakeningBonus: 0,
  resistPeriodicBonus: 0,
  resistStunBonus: 0,
  level1: 65,
  inCombat: false,
  unk5: 16777216,
  hpBonus: 0,
  mpBonus: 0,
  condition: 120,
  contitionMax: 120,
  stamina: 2000,
  staminaMax: 1500,
  staminaBonus: 500,
  infamy: 0,
  itemLevelInventory: 458,
  itemLevel: 458,
  edge: 0,
  unk7: 0,
  unk8: 65472,
  unk9: 0,
  unk10: 0,
  level2: 65,
  flightEnergy: 1000,
  unk13: 0,
  unk14: 1,
  fireEdge: 0,
  iceEdge: 0,
  lightningEdge: 0 }

**Comment by LeandraTS** [comment]
I got similar error as sunnydelete:

To get the error message, you have to actually log into the game, and start to attack a mob, I tested it out on the T3 bams on Island of Dawn.

Neither MP or HP activates.

Once you tab out you will see the error above sunnydelete posted.

As for myself.
I downloaded a fresh copy from your updated scripts, and deleted the old folder completely and unzipped to new folder in Mods.

Don't know if this helps any but this  the info at load up of Caali's Proxy on my computer.

[update] Proxy self-update started (Branch: master)
[update] Proxy is up to date (Update server 0)!
[update] Auto-update started!
[update] Auto-update complete!
[proxy] Tera-Proxy configured for region NA!
[proxy] hosts file patched
[proxy] listening on 127.0.0.20:9250
[proxy] listening on 127.0.0.20:9251

**Comment by Fukki** [comment]
i just remove contract check for this time and should be not have error
need to check something before add it back :/

**Comment by Fukki** [comment]
this problem should be fixed now
i will close this issue in 24 hr if not any problem

**Comment by Fukki** [comment]
fixed again should be not error :/

**Comment by LeandraTS** [comment]
Hi again Fukki,
Here is exact process I did plus error.

I deleted original auto-pot-master folder
I then downloaded a zip of your new update
I extracted zip to new auto-pot-master folder
I then loaded up caali proxy
then tera launcher
loaded into tera
I opened up inventory to make sure pots where there to be used
got hp and mp down to cover when they were supposed to kick in.
Nothing happened.
Here is full message log of error.

`[update] Proxy self-update started (Branch: master)
[update] Proxy is up to date (Update server 0)!
[update] Auto-update started!
[update] Auto-update complete!
[proxy] Tera-Proxy configured for region NA!
[proxy] hosts file patched
[proxy] listening on 127.0.0.20:9250
[proxy] listening on 127.0.0.20:9251
[connection] routing 127.0.0.1:55111 to 208.67.49.50:10001
[dispatch] switching to protocol version 341698
[mods] Loaded module "tera-game-state"
[mods] Loaded module "Command" (command)
[mods] Loaded module "AutoPOT" (AutoPOT)
[mods] Loaded module "CaaliStateTracker"
[mods] Loaded module "CaaliLogger"
[dispatch] handle: error running hook for S_PLAYER_STAT_UPDATE<10>
hook: (anonymous) in autopot
data: { hp: 139399n,
  mp: 3495n,
  unk1: 0,
  maxHp: 139399n,
  maxMp: 3495,
  power: 60,
  endurance: 30,
  impactFactor: 80,
  balanceFactor: 85,
  runSpeed: 110,
  walkSpeed: 52,
  attackSpeed: 90,
  critRate: 50,
  critResist: 70,
  critPower: 2,
  attack: 129902,
  attack2: 129902,
  defense: 53865,
  impact: 50771,
  balance: 68433,
  resistWeakening: 45,
  resistPeriodic: 45,
  resistStun: 45,
  powerBonus: 99,
  enduranceBonus: 98,
  impactFactorBonus: 0,
  balanceFactorBonus: 0,
  runSpeedBonus: 110,
  walkSpeedBonus: 0,
  attackSpeedBonus: 31,
  critRateBonus: 282,
  critResistBonus: 178,
  critPowerBonus: 0,
  attackBonus: 80377,
  attack2Bonus: 80377,
  defenseBonus: 65985,
  impactBonus: 0,
  balanceBonus: 0,
  resistWeakeningBonus: 0,
  resistPeriodicBonus: 0,
  resistStunBonus: 0,
  level1: 65,
  inCombat: false,
  unk5: 16777216,
  hpBonus: 0,
  mpBonus: 0,
  condition: 120,
  contitionMax: 120,
  stamina: 0,
  staminaMax: 3000,
  staminaBonus: 0,
  infamy: 0,
  itemLevelInventory: 440,
  itemLevel: 440,
  edge: 0,
  unk7: 0,
  unk8: 65472,
  unk9: 0,
  unk10: 0,
  level2: 65,
  flightEnergy: 1000,
  unk13: 0,
  unk14: 1,
  fireEdge: 0,
  iceEdge: 0,
  lightningEdge: 0 }
error: Cannot read property 'id' of undefined
    at Object.AutoPOT.mod.hook.e [as callback] (Y:\CaaliTeraProxy\mods\auto-pot-master\index.js:80:101)
[dispatch] handle: error running hook for S_PLAYER_STAT_UPDATE<10>
hook: (anonymous) in autopot
data: { hp: 139399n,
  mp: 3495n,
  unk1: 0,
  maxHp: 139399n,
  maxMp: 3495,
  power: 60,
  endurance: 30,
  impactFactor: 80,
  balanceFactor: 85,
  runSpeed: 110,
  walkSpeed: 52,
  attackSpeed: 90,
  critRate: 50,
  critResist: 70,
  critPower: 2,
  attack: 129902,
  attack2: 129902,
  defense: 53865,
  impact: 50771,
  balance: 68433,
  resistWeakening: 45,
  resistPeriodic: 45,
  resistStun: 45,
  powerBonus: 99,
  enduranceBonus: 98,
  impactFactorBonus: 0,
  balanceFactorBonus: 0,
  runSpeedBonus: 110,
  walkSpeedBonus: 0,
  attackSpeedBonus: 31,
  critRateBonus: 282,
  critResistBonus: 178,
  critPowerBonus: 0,
  attackBonus: 80377,
  attack2Bonus: 80377,
  defenseBonus: 65985,
  impactBonus: 0,
  balanceBonus: 0,
  resistWeakeningBonus: 0,
  resistPeriodicBonus: 0,
  resistStunBonus: 0,
  level1: 65,
  inCombat: true,
  unk5: 16777216,
  hpBonus: 0,
  mpBonus: 0,
  condition: 120,
  contitionMax: 120,
  stamina: 0,
  staminaMax: 3000,
  staminaBonus: 0,
  infamy: 0,
  itemLevelInventory: 440,
  itemLevel: 440,
  edge: 0,
  unk7: 0,
  unk8: 65472,
  unk9: 0,
  unk10: 0,
  level2: 65,
  flightEnergy: 1000,
  unk13: 0,
  unk14: 1,
  fireEdge: 0,
  iceEdge: 0,
  lightningEdge: 0 }
error: Cannot read property 'id' of undefined
    at Object.AutoPOT.mod.hook.e [as callback] (Y:\CaaliTeraProxy\mods\auto-pot-master\index.js:80:101)
`

**Comment by LeandraTS** [comment]
node -v
v10.11.0

Using the version that came as part of the setup.exe of caali's proxy installation.

All the other modules like autoheal and stuff seem to work fine with no errors.

**Comment by Fukki** [comment]
removed contract check
just dont know why error in NA only :/

**Comment by LeandraTS** [comment]
works perfectly now, no error messages

Don't know if it helps any, but before Caali did the last couple of updates, the setup.exe file said something about NA not having all the map codes anymore since it got brought back from the ban, so had to install as EU then manually change it to NA.

Didn't really understand what it was on about, but could be they not implemented everything that is there on the other servers like gameforge etc.

But I removed everything and re-installed with each new update to make sure everything was updated, so maybe Caali' could shine a light on the problem in their discord channel.

Thanks again for getting it working for us on NA, much appreciated  :)
