### ISSUE TITLE
Something borked with Caali's proxy

### ISSUE THREAD

**Issue by Reny900** [Fukki/auto-pot#5]
```cmd
[mods] ERROR: Module "AutoPot" could not be loaded!
[mods] ERROR: Please contact the module's author: #help channel of https://discord.gg/dUNDDtw
{ Error: Cannot find module 'command'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at new AutoPot (M:\Tera_proxy\CaaliTeraProxy\mods\AutoPot\index.js:3:18)
    at ModuleManager.load (M:\Tera_proxy\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:138:35)
    at installedModules.forEach.mod (M:\Tera_proxy\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:57:22)
    at Map.forEach (<anonymous>)
    at ModuleManager._loadAll (M:\Tera_proxy\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:55:31)
    at Dispatch.ModuleManager.dispatch.on (M:\Tera_proxy\CaaliTeraProxy\node_modules\tera-proxy-game\lib\connection\dispatch\moduleManager.js:18:45) code: 'MODULE_NOT_FOUND' }
```

**Comment by Fukki** [comment]
that not my fault
module command should auto install in Caali's proxy
check your have module command or not
or you module is "command-master" just rename back to "command"

**Comment by Reny900** [comment]
just for sake of it i went onto caali's page and downloaded a out of the box new command and used it, and it was fine and dandy.
got this error instead
```cmd
[update] Updating module auto-pot
[update] - Retrieving update manifest (Server 0)
[update] - Download index - Copy.js
[update] ERROR: Unable to auto-update module auto-pot:
Failed to update the following module files:
 - index - Copy.js
 - StatusCodeError: 404 - {"type":"Buffer","data":[52,48,52,58,32,78,111,116,32,70,111,117,110,100,10]}
[update] Please go to https://github.com/Fukki/auto-pot/issues/ and follow the given instructions or ask for help.
[update] Alternatively, ask here: #help channel of https://discord.gg/dUNDDtw```

**Comment by Fukki** [comment]
![image](https://user-images.githubusercontent.com/26898177/50058809-614fc380-01b0-11e9-8b41-0ac2b5833e39.png)

**Comment by Fukki** [comment]
sorry i put wrong manifest in my last update
should be fix now try to restart your proxy
